### PR TITLE
Create a CI environment to test ICF-workflows

### PR DESCRIPTION
**Pull request by christian-monch**
##### General

Fixes https://github.com/psychoinformatics-de/org/issues/162

This PR adds an appveyor specification that allows testing ICF workflows in a realistic environment. The setup creates representative(*) scanner acquisition data. It runs the ingestion script on the data and sets up an HTTP server with restricted access to the output of the ingestion script.

There are currently two studies available: "study_1" and "study_2". The tests are executed as user `appveyor`. The studies are accessible on the CI environment via `http://localhost/~appveyor/study_1/`  and  `http://localhost/~appveyor/study_2/` (there is currently no https-service running). Access is restricted and requires basic authentication. The username is `test.user` and the password is `secret_1`.

Tests are executed with `pytest`.

#### Task list

This task list is copied from https://github.com/psychoinformatics-de/org/issues/171.

- [x] 2.1 Map a number of example DICOMs from https://github.com/datalad/example-dicom-structural into the test VM, e.g. by curl-ing them to a temporary directory (env: FROM_SCANNER). Add some non-DICOM files, to represent the incoming data at ICF, e.g. scan_1_catalog.xml.
- [x] 2.2. Create an output directory for tar-balls (env: STUDIES_DIR)
- [x] 2.3. Use the ingestion script (https://github.com/psychoinformatics-de/inm-icf-utilities/blob/main/bin/make_studyvisit_archive) to create tar-balls and md5-files, i.e. `bin/make_studyvisit_archive --output-dir $STUDIES_DIR --id study_1 visit_1 $FROM_SCANNER`.
- [x] <strike>2.4 Run the ingestion tests from 1.1.</strike> Not necessary here, those tests can be executed as part of 2.10.
- [x] 2.5. Install an apache server with "Basic" authentication, "Range"-support, ...
- [x] 2.6. Add a user to the system.
- [x] 2.7. Add links to the study, or studies if we simulate more than one study, to the user directory. Edit: add authentication requirement for the study-realm.
- [ ] 2.8. Ensure that we cover the python version of ICF, either by specifically setting the version or by running tests on a range of python versions.
- [x] 2.9. Install the latest datalad and datalad-next, including a git-annex version that matches the git-annex version on ICF. This step will install the latest `datalad`-release and the latest <strike>`datalad_next`-master</strike> `datalad-next` upload to pypi (via `pip install --pre datalad-next`). Using `datalad_next`-master allows to run the easily run the tests on non-released versions of `datalad-next`.
- [x] 2.10. Run tests (found by `pytest`)
- [ ] 2.11. Enable https-support in the apache configuration. **NB**  use the `dicom_server`-fixture to determine server details. that will provide the correct URL in all cases.
- [x] 2.12. Support local test development. (use the `dicom_server`-fixture to determine the server, and -if you want to run tests locally- define the env-var `INM_ICF_TEST_STUDIES` to point to a directory that contains studies as defined in RFD0034 )
- [ ] add docs describing the setup in detail.

(*) representative for the data that the ICF receives from acquisition and on which it starts the workflow

### CODE REVIEW

**Comment by christian-monch** [comment]
The current state allows testing ICF-workflows. It uses a subset of the DICOMs in `https://github.com/datalad/example-dicom-structural/raw/master/dicoms/`.

- Use a subset of the DICOMs in `https://github.com/datalad/example-dicom-structural/raw/master/dicoms/` to create a scanner-output like structure.
- Uses the ingestion script `bin/make_studyvisit_archive` to create studies from the created scanner outputs. 
- Sets up two studie datasets: `study_1` and `study_2` in `/var/www/data/study_1` and `/var/www/data/study_2`.
- Sets up two links owned by root in `~/appveyor/study_1` and `~/appveyor/study_2` linking to the respective datasets.
- Sets up an http-server with authorization required for the study datasets.

**Comment by christian-monch** [comment]
2.8 still has to be done. Needs input on what python version is used in INM ICF

**Comment by mih** [comment]
> 2.8 still has to be done. Needs input on what python version is used in INM ICF

At present, these systems run Debian 11.6 -- which translates to Python 3.9.2 (by default).

**Review by mih — COMMENTED** [review]
Thanks! Just going through the diff this LGTM!

I would propose to align a few aspects with the familar testing setup used for datalad (i.e. deploy git-annex via datalad-installer, etc.)

I will enable appveyor for this repo so we can see this in action.

**Comment by christian-monch** [comment]
> Thanks! Just going through the diff this LGTM!
> 
> I would propose to align a few aspects with the familar testing setup used for datalad (i.e. deploy git-annex via datalad-installer, etc.) [...]

Good suggestion. I actually tried that but with no success. Not sure where the error was, decided then to move on and install git-annex "manually". Will take another look.

> 
> I will enable appveyor for this repo so we can see this in action.

👍🏻

**Comment by mih** [comment]
So the machinery runs, which should be good enough for now. I will merge this PR, and any further improvement can come as increments rather than having to go through this PR. Thx!

**Pull request merged**
